### ISSUE TITLE
D3DCOMPILER_44.dll is missing

### ISSUE THREAD

**Issue by KichangKim** [sharpdx/SharpDX#468]
Hi, I tested sharpdx in Windows 8.1 Pro x64, SharpDX 2.6.2 (from nuget), used DirectX11_2-net40 libraries, but it says that D3DCOMPILER_44.dll is missing and I can't run progmram anymore. Is this bug?

**Comment by ikeough** [comment]
@xoofx This has never been fixed 

Somehow, a while back, I managed to get the correct version of sharpdx_direct3d11_1_effects_xxxx.dll and make everything work (I believe it was linked in forum post) without the error mentioned here. That link is now dead. Recently, I updated my project to use the SharpDX 2.6.3 NuGet package, instead of the dlls I was previously using, and my application no longer works with the "D3DCompiler_44.dll missing" error. What's strange is that another project that I have, which uses the 2.6.3 SharpDX NuGet package does not display this error and all of the application's configurations are the same (i.e. AnyCPU, .net 4.5, etc.).

I require `SharpDX.Direct3D11.Effects`, so not using it is not an option. I'd be happy to lend a hand compiling whatever needs to be compiled and helping to fix the NuGet packages, but I'd need some direction on what actually needs to happen (i.e. compile against D3DCompiler_47.dll).

**Comment by xoofx** [comment]
As I don't use this API, I would be glad if someone has some time to look at this.

The code in SharpDX of Effects is in https://github.com/sharpdx/SharpDX/tree/master/External/Effects11  and should use the latest https://github.com/Microsoft/FX11.

These DLLS are then used in SharpDX.Direct3D11.Effects, [D3DX11Effects.cs](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct3D11.Effects/D3DX11Effects.cs).

You can reopen an issue to follow this.

**Comment by ikeough** [comment]
@xoofx. I'm not going to suggest that this be an official recommendation, but I found that if you rename `D3DCompiler_46.dll` to `D3DCompiler_44.dll` and put it in your application directory, it works :) I'm not going to go recompiling things at present, because this works for me AND because @OndrejPetrzilka did some compiling here a while back (a year ago) in https://github.com/OndrejPetrzilka/SharpDX/commit/e050b96920b8a892238d33d2d366a2406e284e87. Is it possible that that work didn't make it into the NuGets?
