### ISSUE TITLE
Migrated to DirectX11_2 and no more Texture2D.FromFile

### ISSUE THREAD

**Issue by BwainHertz** [sharpdx/SharpDX#527]
Hi,

I'm newbish so sorry if I'm missing the obvious.

I've migrated my code to use the DirectX11_2-Signed-net40 assemblies and find that Texture2D.FromFile and Texture2D.LoadTextureFromTexture are no longer available.

What's the recommended way to load textures? All my googling just refers to old versions or potential use of the Toolkit (currently I am using the RenderForm to create a Tool with multiple form interfaces rather than a game).

Many thanks in advance an hope I am asking in the right area.

Regards,
BH.

**Comment by xanather** [comment]
I see Texture2D exposes
public Texture2D(Device device, Texture2DDescription description, params DataRectangle[] data)

Could manually read data into DataRectangle from a image file using other .net BCL's then initialize it with that constructor.

**Comment by BwainHertz** [comment]
Thanks for your reply xanther. I expect your are correct, but I have no idea what other libraries to use in order to read the various possible jpg/dds/png formats that people might use.

DirectTex seems to cover this and I found a link showing how they could be loaded ...

http://stackoverflow.com/questions/9602102/loading-textures-with-sharpdx-in-windows-store-app

... but I really thought there would be a clear direction as to how this should be handled going forward. I also need to work out how to Save() and use the LoadTextureFromTexture function to combine multiple images into one larger one. It's not as simple as I had hoped but this is often the case. ;)

**Comment by xoofx** [comment]
The general trend is that Direct3D is getting more and more bare bone instead of an all in one 3D API. So they have been removing lots of stuffs starting from Direct3D10 and It will be even more bare bone with Direct3D12. So the way to load textures todays is to handle it in your application (or use a rendering engine). SharpDX is following this trend, just matching DirectX API.

Note that DirectXTex was ported to the Toolkit and you can always extract it from the Toolkit and use it in your app. It is just a couple of classes that could stay internals in your app.

**Comment by BwainHertz** [comment]
OK, Thanks very much for your advice!
