### ISSUE TITLE
WPFHost sample flickering on window resize

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#533]
I noticed that resizing the WPFHost demo in SharpDx causes sometimes the background of the window to be shown.

You can see it in the following video at seconds 11 and 14
http://screencast.com/t/Zo7mhDp3Iq

Does this have something to do with the "broken" implementation of the WPF/D3DImage hosting that you referred to in my previous issue #519 ?
Is this a Microsoft issue or a SharpDx one?
Is there anything I can do to avoid this?

Thanks for any help you can provide.

**Comment by xoofx** [comment]
The sample may not be the best WPF-D3D interop implem (it is a really old implem contributed by someone external to the project), so I don't know about this particular problem of resizing and if it is fixable. I have stopped to try to fix anything about WPF and D3D through D3DImage, so no longer provide any help about it, as it is really a waste of time (trying to fix a bit these kind of things just to discover that in the end, it is unusable...etc.)

**Comment by devdept** [comment]
Hi xoofx,

As mentioned in one of my previous posts, we have money to put on this project. Are you available to fix this issue for us at an hourly rate? Or does this issue belong to Microsoft D3DImage control itself?

**Comment by xoofx** [comment]
I really can't do anything about this. May be the background problem could be fixed, but then, are you expecting to just display a little triangle? Because if you expect to display something that can be GPU consuming, no matter how hard you will try, your whole WPF application will start to slow down and D3DImage will flicker, which is something much more annoying that the little flicker that you are currently experiencing. Again, depending on your needs, D3DImage may be fine, but don't expect it to be flicker/wpf-stutter free.
