### ISSUE TITLE
SharpDX.Direct2d1.Effects namespace is empty in 2.6.3 version

### ISSUE THREAD

**Issue by Niharp21** [sharpdx/SharpDX#592]
We are using 2.6.3 version of SharpDX and we have found that there are no classes under SharpDX.Direct2d1.Effects namespace.

**Comment by xoofx** [comment]
If you are not using nuget, they are part of the DirectX11_2 bin folders, otherwise you need to configure SharpDX-nuget to use the proper assembly versions by adding `<SharpDXDirectXVersion>DirectX11_2</SharpDXDirectXVersion>` as described in https://github.com/sharpdx/SharpDX/wiki/Installation#advanced-configurations

**Comment by Niharp21** [comment]
Thanks. But as per this link DirectX11_2 versions require .Net 4.0+ framework. We work on 3.5 framework so is it OK?

**Comment by xoofx** [comment]
Unfortunately, there is no 3.5 version of DirectX11_2. Note also that 3.5 support will be drop-off in next SharpDX 3.0 version.

**Comment by Niharp21** [comment]
Thanks for the information.
