### ISSUE TITLE
XAudio2.7 and .NET Core

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#594]
I am trying to create a XAudio2.7 audio device using the new .NET Core 5 workflow (I used the console app package template in VS2015 RC).

I go and reference SharpDX.XAudio2 package through NuGet/package manager and I am unable to retrieve the XAudio2Version type. I can create a XAudio2 object while debugging fine, but am unable to specify the version to use. It seems to be hardcoded to XAudio2.8 when looking through the assembly with ILSpy. It strange because the source tells a completely different story https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.XAudio2/XAudio2.cs#L64. Considering that .NET Core 5.0 runs on Windows 7 is it possible to have an option to allow the usage of XAudio2.7 for the .NETCore/PCL distribution of SharpDX?

The PCL/NETCore distribution of SharpDX will most definitely be used by some developers outside the WinStore now with .NET Core 5 becoming usable, especially for people looking to develop a cross platform engine which makes use of multiple API's depending on the platform.

I hope this is possible, thanks

**Comment by xanather** [comment]
I forgot to mention this is on the latest alpha 3.0.0.0 version

**Comment by xanather** [comment]
I figured out the reason why XAudio2Version type does not exist is because the NuGet packets have not been updated since the Version2_7 option was added to XAudio. The latest version still won't allow you to initiate a Version2_7 XAudio2 device however, see: https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.XAudio2/XAudio2.cs#L80.

**Comment by xoofx** [comment]
Sorry for the state of the 3.0 compilation process, still didn't have time to work on it for several weeks. 

If you download the latest binary zip from sharpdx.org, you should get the latest build against the sources. Nuget 3.0 is not up-to-date (don't remember exactly why)

**Comment by xanather** [comment]
Thanks for the reply, regarding getting the latest binaries. I already have those, however it is still impossible to create a XAudio2.7 device on the NETPortable library of SharpDX.XAudio2 due to the link I pasted above (https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.XAudio2/XAudio2.cs#L80) which is what this issue is about. I realize you have been busy as of late which is why I wanted to try attempt to solve this myself since it looks pretty straight forward. The problem lies however with how complex it is to compile SharpDX and really think it should be cleaned up/simplified and explained somewhere so others can contribute easier.

**Comment by xoofx** [comment]
Hm, not sure to understand... Both SharpDX Desktop and Store assemblies have been compiled with PCL.So the SharpDX Desktop assemblies should be PCL (as setup in the [build file](https://github.com/sharpdx/SharpDX/blob/master/Build/SharpDX.PreSettings.targets#L39), assuming that SharpDXDesktopOnly is false, which should be the case afair)
What you can't have is a general PCL library that supports both 2.7 and StoreApps.

For the compilation, well, It was never easy, as SharpDX had to support many different platforms that were coming with different headers files...etc. So in the past, It requires to install many SDK (DirectX SDK, Windows 7 SDK, Windows 8 SDK). In order to support Direct3D12, the compilation process has been simplified, so we just rely on Windows 10 SDK, but because the SDK is not yet stabilized (there is no stable version of it so far) we have still to deal with this problem for a few months. 

I'm currently working on moving SharpDX.org website to a github-pages so that SharpDX users will be able to more easily contributes to the documentation.

**Comment by xanather** [comment]
Moving to github pages sounds like a good idea, many docs on the SharpDX.org are outdated. Also I did not even realize the Desktop builds were PCL supported so this might not even be an issue. I was the one to misunderstand sorry, I thought the StoreApp was the PCL libraries, not 100% sure what NuGet was giving me anyway. I will test the latest against .NET Core 5 today.

**Comment by xanather** [comment]
Can't believe I missed it, all the Desktop binaries are NETPortable! Case closed.
