### ISSUE TITLE
AdapterDescription1 returned by Factory1.GetAdapter1 has corrupted Description

### ISSUE THREAD

**Issue by xenux** [sharpdx/SharpDX#598]
![untitled](https://cloud.githubusercontent.com/assets/8893272/8054325/baf70170-0ed2-11e5-96a3-e80218c6d958.png)

**Comment by xoofx** [comment]
As the native code of the `Description` field is a 128 char array. It doesn't say that it is a null terminated string, so that's why there is all these `\0`. The current code is generated automatically for this struct, so It would require to handwrite the marshalling to handle this case. A workaround is to strip the `\0` by using something like this `adapterDesc.Description.Trim('\0');`
