### ISSUE TITLE
[DirectInput] MousePosition value from mouseState isn't correct

### ISSUE THREAD

**Issue by Reaw** [sharpdx/SharpDX#612]
When I'm tryin to add hover state to the gameobjects in my game,when using method
mousestate = mouse.GetCurrentState();
Rectangle.Contains(mousePosition) where mousePosition = new Vector2(mousestate.X,mousestate.Y)

Console says that hover is happening everytime,even if mouse isn't on the SharpDX Window.

**Comment by Gavin-Williams** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ee417014%28v=vs.85%29.aspx

Note  Use of legacy DirectInput is not recommended, and DirectInput is not available for Windows Store apps.

And i can attest to having problems with DirectInput which cannot be solved. Because it's an old system that isn't being updated. I've had crazy problems with it a few years ago, since then I've never used it. It's not needed.

**Comment by Reaw** [comment]
@Gavin-Williams 
So how can I get the mouse Position to make Buttons (using only Game class) ?

**Comment by Gavin-Williams** [comment]
Game class ? Are you using the Toolkit ? If so, the toolkit is deprecated (mainly so that the sharpdx author can focus on sharpdx itself and on his other work with the Paradox3d game engine http://paradox3d.net/ There may be a branch of the toolkit and ongoing support, but I don't have the link and I couldn't find it just now.

You might occasionally get toolkit support here, but it's not guaranteed, they might just tell you that it's not supported anymore.

The way that Microsoft recommend getting keyboard and mouse info and what I tend to use is the Windows messaging system. So in my current project I subscribe to the events like this ...

[code]
                 // register events
                coreInput.PointerPressed += new Windows.Foundation.TypedEventHandler<object, PointerEventArgs>(OnPointerPressed);
                coreInput.PointerReleased += new Windows.Foundation.TypedEventHandler<object, PointerEventArgs>(OnPointerReleased);
                coreInput.PointerMoved += new Windows.Foundation.TypedEventHandler<object, PointerEventArgs>(OnPointerMoved);

...

        private void OnPointerPressed(object sender, PointerEventArgs e)
        {
            e.Handled = true;
            PointerPointProperties properties = e.CurrentPoint.Properties; //e.GetCurrentPoint(xamlSwapChainPanel).Properties;
            if (properties.IsLeftButtonPressed)
            {
                mouseNext.LeftButtonPressed = true;
                mouseNext.IsLeftButtonDown = true;
            }
            if (properties.IsRightButtonPressed)
            {
                mouseNext.RightButtonPressed = true;
                mouseNext.IsRightButtonDown = true;
            }
        }

[/code]

Your case might not be exactly like this, but it will be something similar. My example code is WinRT code, while you might be working on Win32, maybe using WinForms or WPF (I'm not sure how the toolkit sets up the window). Additionally, I use a background thread, as per the current recommendation when working with WinRT / xaml, while most example code for earlier versions of Windows didn't do this, and just gather input on the main thread.

You can also use RawInput https://msdn.microsoft.com/en-us/library/windows/desktop/ms645543(v=vs.85).aspx which is a generic way of gathering input from various devices including mouse, keyboard, joystick, microphone etc. I have used RawInput as well in the past, it's good, if a little laborious to set up. It needs to be in order to enable gathering input from many different kinds of devices.

There are people using the toolkit, so you might still get a response to help with your particular issue, but It's probably worthwhile looking at the windows messaging system to get the mouse info, it's a more reliable method moving forward. There maybe something like a WinForm class or Form class in the toolkit or Window class that exposes these events. I'll take a quick look myself to see if i can find it myself.

**Comment by Reaw** [comment]
@Gavin-Williams 
Will this work when I want to make some Buttons in the 2D space?
In the XNA this is simple but I see in SharpDX this is much more complicated and I still don't know how to do this.

**Comment by Gavin-Williams** [comment]
Yep, once you work it out, it's fine for buttons in your user-interface system. And it can be applied to 2d as well as 3d (via projecting your mouse ray through your view frustum).

Once you get your input code working, you can improve it until it works the way you want it.

**Comment by xoofx** [comment]
DirectInput should not be used for getting mouse coordinates. Use HWND on desktop.
