### ISSUE TITLE
[Direct3D12] Missing loading Texture from File

### ISSUE THREAD

**Issue by RobyDX** [sharpdx/SharpDX#632]
I can't find a method to load a D3D12 Resources from file inside the library. Do you plan to add one in future?
Thx

**Comment by xoofx** [comment]
Well, not sure which D3D12 API you are referring to?

**Comment by RobyDX** [comment]
Sorry I didn't explain well, my English is really bad (I'm italian). 
I mean that Microsoft haven't added a method to load Texture from file in D3D12. To test SharpDx I've written one for my own to load DDS (just converting the cpp class from Microsoft MSDN). 
I wanted to ask if you will add one in future like an utility or do you prefer to leave Direct3D12 clean from method that doesn't exist in original API.

**Comment by xoofx** [comment]
I plan to keep Direct3D12 as bare as minimum (No utility methods....etc.). The reason is that it is already difficult to maintain SharpDX while I have a bunch of stuff to develop on my sparetime (and actually, I'm getting quite bored by maintaining this wrapper...) and at work, I'm already working on wrapping SharpDX around a more featured engine [Paradox](https://github.com/SiliconStudio/paradox/) and provide all utilities methods there (so that I don't duplicate my work with SharpDX)

**Comment by discosultan** [comment]
@RobyDX Care to share your SharpDX Direct3D12 port of the DDSTextureLoader?
