### ISSUE TITLE
WPF control issues

### ISSUE THREAD

**Issue by devdept** [sharpdx/SharpDX#656]
Hi Alexandre,

Regarding the issue below (we care a lot about), we are in contact with Microsoft Redmond (WA) to solve it. I would need you to contact us to arrange an appointment with a the Microsoft's developers so you can explain them what's wrong with the D3DImage control and discuss with them how to improve it. Please drop us a line at info [at] devdept [dot] com ASAP.

Thanks so much in advance.

https://github.com/sharpdx/SharpDX/issues/519

**Comment by weltkante** [comment]
Microsoft has been releasing [source code](https://github.com/Microsoft/WPFDXInterop) for WPF DX interop (officially for the [next 4.6.1 version](http://blogs.msdn.com/b/wpf/archive/2015/10/29/wpf-in-net-4-6-1.aspx) but since it has public source code it might work on earlier versions?), maybe you want to check this out instead of using the SharpDX hosting. They use the same underlying technology (WPF D3DImage control) but may differ in the implementation details, so it may be useful to compare both implementations.

Note that you can still use SharpDX, just use the Microsoft control for hosting.

If you are experiencing the same issues with the Microsoft control hosting you might have better luck getting the problem fixed by posting an issue against their library.

**Comment by QuantumDeveloper** [comment]
@weltkante as I can see they use delegate to render and it fires only 60 frames per second.
When control resize, it changes IntPtr for surface to render, which will lead to swapchain recreation. So, I dont think they really changed something here - they just write the same DX9 xontrol for DX11. Also I dont think they really understand what is efficient DX rendering, because example they upload present highly inefficient way of rendering. So, I am afraid, but seems nothing will change in better way, unfortunately.

**Comment by weltkante** [comment]
Seriously, you need to work on your attitude. I just hinted you to an alternate way to resolve your problems directly with Microsoft instead of waiting for a developer who already stated (in the other issue) he is not interested and has no time.

Most of your arguments are wrong or don't matter. If you are currently using SharpDX hosting to do WPF interop you are already using a D3DImage. Switching over to Microsofts implementation allows you to file bugs against them and resolve your issues with them, but here you complain about totally unrelated stuff like performance or their implementation details (some of which you clearly don't understand).

Anyways I give you even another suggestion: if performance is so important to you, you should switch over to UWP, you got a much better Direct3D interop story there and have full control over your swap chains and everything, while still being able to mix in XAML UI.

If you need WPF to stay compatible to older OS versions you should stop complaining and start figuring out whats wrong, and then get it fixed with Microsoft. Don't wait for someone else to do your work.

**Comment by QuantumDeveloper** [comment]
First of all:
1. I am not complaining. I just pointing disadvatages of their solution and I have already created a several issues on MS branch at github.
2. I am not using D3DImage to render DX content in WPF.

**Comment by weltkante** [comment]
> 1. I have already created a several issues on MS branch at github.

I saw the other issues, some are correct, some look questionable, on the latter I added some comments.

> 2. I am not using D3DImage to render DX content in WPF.

Ok I misunderstood this then, sorry. However I don't think you'll get an alternative for D3DImage interop with WPF anytime soon, it doesn't look like MS is investing much resources there.

If you don't really need WPF you should consider UWP, they've done a lot of things much better.

**Comment by QuantumDeveloper** [comment]
I know about UWP and like thair solution, but I dont like UWP limitaions. On WPF I have more freedom in that what I can do with my PC resources. I dont like an idea of being locked inside virtual sandbox of application with no access to other parts of PC if I need them.

**Comment by weltkante** [comment]
UWP desktop applications are not locked.

**Comment by QuantumDeveloper** [comment]
Ok, but I need VS like tabbed docking control, which UWP hasnt. It present only on WPF dektop for now if I didnt miss anything. Also what about licensing and distributing my app to other people with store? Could I do that on UWP?

**Comment by weltkante** [comment]
Those controls can certainly be implemented but it may indeed take a while until some become available. About distribution I'm not sure how you distribute UWP applications outside the store, but I heared that it is possible to allow business selling applications without having to go through the store.

A quick google search showed up [sideloading](https://msdn.microsoft.com/library/windows/apps/hh454036.aspx#InstallRemote):
> If you have an app that you don’t want to sell in the Store, like a line-of-business (LOB) app, you can sideload that app so that other users in your company can use it.

I don't know if having customers to "unlock" sideloading in the control panel would be prohibitive for you, so you might have to look into it more before its clear whether it is a possible option.

Personally I don't see much problems with restricting myself to allowed APIs though, considering they even opened up JIT code generation in store apps, they are becoming more permissive now.

Anyways I guess this starts to go off topic ;-) UWP is just an option and may not be ideal for everyone (for example if you still want to support older OS versions its no option anyways). Just wanted to make sure you (and possibly other people coming across this issue) are aware of the alternatives.
