### ISSUE TITLE
Load 3D FBX Model

### ISSUE THREAD

**Issue by Skinz3** [sharpdx/SharpDX#776]
Hi, im not able to load a 3D Model with SharpDX 2.6.3.0

Im using the toolkit, =>
 Content.Load<Model>(MI.FBX);
 
and ive got this error:Unexpected chunk [Kayd/0x6479614B] instead of [TKMD/0x444D4B54]

**Comment by Reaw** [comment]
@Skinz3 I'm not the expert of SharpDX but I think that you won't get any help here, because the toolkit is deprecated now :(.
I've found some article about importing models here:
https://interplayoflight.wordpress.com/2013/03/03/sharpdx-and-3d-model-loading/
I'm not sure if it is written in Toolkit, but u have to know that the Toolkit is written in the pure SharpDX, so you will be able to rework this code.

**Comment by Skinz3** [comment]
Okey, thanks man ;)

**Comment by xoofx** [comment]
The Toolkit is deprecated.
