### ISSUE TITLE
Interest in (partial) SharpDX port of DirectXTK?

### ISSUE THREAD

**Issue by RobJellinghaus** [sharpdx/SharpDX#786]
As we all know the old SharpDX.Toolkit is abandoned as of 3.0.0.

It turns out there is a well-maintained and up-to-date XNA-like C++ toolkit maintained by some people at Microsoft:  https://github.com/Microsoft/DirectXTK

My application ( http://holofunk.com ) currently uses SharpDX 2.6.3 and the SharpDX Toolkit, and does not run on Windows 10 (due to needing an obsolete DirectX version).  The simplest way to proceed, it seems to me, is to port the SpriteBatch and SpriteFont classes from DirectXTK to SharpDX.

If I did this, would anyone be interested in a pull request?

**Comment by Tiba3195** [comment]
Hey mate, I have the toolkit up and running on windows 10 and Sharpdx 3.0.2.
Also got the content side of things working for fonts and shaders.

I only use it for spritebatching but the rest should work.

**Comment by kobush** [comment]
I have the SharpDX.Toolkit ported to current SharpDX version. Actually it was simple recompile upgrading the NuGet packages (I don't remember if I had to make any code changes). It runs fine in my UWP apps on Windows 10 and phone.

**Comment by Tiba3195** [comment]
Is there an echo in here?

**Comment by RobJellinghaus** [comment]
Well this is certainly outstanding!  Tiba3195 did you have to make any code changes or was it a simple recompile as well?  Have either of you told Alexandre (xoofx) about this?  Seems like it could make it back into the 3.0.2 distribution....

In any case, it would be great if either of you have a repository with your code.  I am most of the way towards porting to FNA at the moment, but a ready-to-go SharpDX 3.0.2 Toolkit would be preferable to FNA, because it'd let me get at all of DirectX much more easily.  Thanks extremely much!

**Comment by Tiba3195** [comment]
Hey mate, if u look at the toolkit got site go to the pr tab and in there u will find two different ways of fixing the toolkit for sharpdx 3.0.2.

I'm in bed right now so I'm not sure what one I used, I'll check once I get up. I think I'm using the one with universal app support.

My toolkit is using a custom sharpdx build but I don't think that will be an issue.

I had to hand edit my project files to include the sharpdx toolkit build targets so that I get font and toolkit effect compiling.

Will be more than happy to help get u up and running.

If u look at my git repos u will find a .net wrapper for amd graphics services and spherical harmonics maths lib that was I'm dx9 and xna.

**Comment by xoofx** [comment]
There is already a [PR on the Toolkit](https://github.com/sharpdx/Toolkit/pull/3) for that, duplicating the work on this would be a bad idea (somewhat, SharpDX Toolkit was already a partial port of DirectXTK). Please follow/comment/help there

**Comment by RobJellinghaus** [comment]
Tiba and Kobush, I will try to contact you by email.  I just ran into the inability to build SharpDX from source with just VS2015 (see the issue just opened on this).  Given this additional issue, I am going to step back from SharpDX until VS2015 development is viable with it.  However, once SharpDX builds under VS2015 on Win10, I will definitely take another look at both of these PRs.

**Comment by Tiba3195** [comment]
You just need to unblock all the .dll and .exe files that come with the SharpDX SDK, I found a powershell context menu add-on that lets me do it by folder

Builds fine for me VS2015 windows 10, if It didn't I would be stuck because VB.net hates having both a byref and byval method or function with the same name.
