### ISSUE TITLE
Update GCCXML to support Visual Studio 2015

### ISSUE THREAD

**Issue by wjk** [sharpdx/SharpDX#794]
The title really says it all. I am unable to install Visual Studio 2012 simply to build this one project. GCCXML expects to be used only with Visual Studio 2012's version of MSVC, and it isn't, and cannot be easily made, compatible with Visual Studio 2015's version of MSVC. This is blocking me from building SharpDX for myself, which I need to do as I am expanding on @manu-silicon's work from #651.

**Comment by wjk** [comment]
I have started work on making this compatible with Visual Studio 2015 myself. Following the changes [introduced in this commit](https://github.com/wjk/SharpDX-CoreCLR/commit/bbf84f34ed8ebcc033c203d23792cff3ab760d35), the build proceeds until it reaches the step where it runs `gccxml`. `gccxml` tries to parse the Microsoft CRT headers, and it chokes on the following code in `stddef.h`:

```c++
namespace std {
    typedef decltype(__nullptr) nullptr_t;
}
using ::std::nullptr_t;
```

Apparently, `gccxml` has no idea what `__nullptr` is supposed to be. No amount of `#define`-based renaming will cause it to parse this successfully, nor will replacing `stddef.h` with a file in the `overrides` directory, [as was tried here](https://github.com/wjk/SharpDX-CoreCLR/blob/master/External/gccxml/share/gccxml-0.9/vc14/overrides/stddef.h). I am using the 10.0.10586.0 Windows 10 SDK. Any pointers on how I could get this to work? Thanks!

**Comment by RobJellinghaus** [comment]
Thank you for looking into this.  I was just wondering why gccxml was giving me an "A fatal error occured" error when trying to build with the Win10 SDK 14393 on Windows 10 and Visual Studio 2015.

The first errors I see are of the form:

2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core.h(2,24): error : in gccxml  objidlbase.h: No such file or directory
2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core.h(3,20): error : in gccxml  wtypes.h: No such file or directory
2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core.h(4,22): error : in gccxml  winerror.h: No such file or directory
2>SharpGen(1,1): warning : in gccxml In file included from sharpdx.h:3,
2>SharpGen(1,1): warning : in gccxml                  from sharpdx-root.h:26:
2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core-direct3d.h(2,23): error : in gccxml  d3dcommon.h: No such file or directory
2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core-direct3d.h(3,21): error : in gccxml  d3d10_1.h: No such file or directory
2>C:\SourceTree\SharpDX\Source\SharpDX\sharpdx-core-direct3d.h(4,19): error : in gccxml  d3d10.h: No such file or directory

So it's hard for me to tell whether these are genuine errors, or a misconfiguration on my end, or some other environmental difference.  In any case I will certainly pull anything you come up with if you want someone to test your changes.  In the meantime though I will go back to FNA since at least that builds properly under VS2015.

**Comment by xoofx** [comment]
I just tested on a brand new machine I'm installing here, having installed only VS 2015 and it works fine.

When installing VS 2015 you need to check the box "Tools for Windows 8.1" to install proper bits required by gccxml.

**Comment by RobJellinghaus** [comment]
I have those bits installed on this machine.  I went to VS 2015 Setup to install them, assuming they weren't there, but they are.  Under "Windows 8.1 and Windows Phone 8.0/8.1 Tools", the "Tools and Windows SDKs" checkbox is very much checked.

So whatever my issue is, this isn't it, and closing this is premature.

To be complete, the Features installed in my VS2015 Update 3 installation (e.g. the actually checked checkboxes) are:

Common Tools for Visual C++ 2015
Visual F#
Microsoft Web Developer Tools
Windows 8.1 and Windows Phone 8.0/8.1 Tools > Tools and Windows SDKs
Clang with Microsoft Codegen
GitHub Extension for Visual Studio
Visual Studio Extensibility Tools Update 3

**Comment by xoofx** [comment]
@RobJellinghaus  can you post the full build log? (and check also this [issue](https://github.com/sharpdx/SharpDX/issues/682))

**Comment by Tiba3195** [comment]
Just going to put it out there but have you unblocked all the .dll\.exe that come with the sharpDX sdk?
I could not build until I did that.

**Comment by RobJellinghaus** [comment]
I am sorry to be ignorant here, but what _exactly_ do you mean by "unblocked"?  I am not familiar with what you are describing.  How exactly do you do this?  And what error do you get if you don't do it?

Here is the gist for my build issue, which I just replicated on a fresh machine with VS2015 Update 3 Community Edition + Win10 SDK 14393 + Win8.0/8.1 Tools & SDKs:

https://gist.github.com/RobJellinghaus/0ce00d78919da541a58b53da4082c252

**Comment by manu-silicon** [comment]
Could you check that in the following folder:
```C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\```
You have the missing offending files (like ObjIdlbase.h)?

**Comment by RobJellinghaus** [comment]
```
C:\Program Files (x86)\Windows Kits\10\Include>dir /s ObjIdlbase.h
 Volume in drive C has no label.
 Volume Serial Number is 2CB1-B739

 Directory of C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um

07/27/2016  09:14 PM           230,035 ObjIdlbase.h
               1 File(s)        230,035 bytes

     Total Files Listed:
               1 File(s)        230,035 bytes
               0 Dir(s)  355,371,483,136 bytes free
```

So it is there, but under the current version number, 10.0.14393.0, rather than the one that SharpDX seems to be expecting:

```
6>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\shared"]
6>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um"]
```

I did "findstr /s 10586 *.targets *.*proj *.build" in the SharpDX root directory, but it didn't turn up any specific references to 10586.  How should this Win10 SDK path be updated?

**Comment by xoofx** [comment]
Ok, this should only work with 10586 which is part of the VS 2015 Update 3. You should check that your install has:

- Programming Languages / Visual C++ / Common Tools for VS 2015
- Windows and Web Development / Universal Windows App Development Tools (ensure that Windows 10 SDK (10.0.10586) is selected)
- Windows 8.1 and Windows Phone 8.0/8.1 Tools

**Comment by RobJellinghaus** [comment]
I see.  The problem is that the latest VS2015 Community Edition With Updates, that can be downloaded on the web, no longer includes the 10.0.10586 Win10 SDK; it includes the updated 10.0.14393 Win10 SDK only.

The 10.0.10586 SDK is downloadable from the archive link: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive -- I think this is the link you need to include in your documentation, if SharpDX really only works with that specific SDK version.  However, I am a bit nervous that SharpDX doesn't work with the 10.0.14393 version, as there are probably a lot of SDK changes related to the updates in Win10 itself.  

On the other hand, I know SharpDX is not your main priority and is not making you any money, so keeping up with Microsoft's incessant (at least biannual) SDK churn is not very motivating for you either :-)
