### ISSUE TITLE
Only one constructor. Is this bug?

### ISSUE THREAD

**Issue by jarmohh** [sharpdx/SharpDX#837]
Look pictures. 
SharpDX.Direct2D1.Factory3 and SharpDX.DirectWrite.Factory3 has only one constructor with nativepointer.
I think there must be other also or I don't understand how to call them.

https://onedrive.live.com/?cid=FD8073F3502D075D&id=FD8073F3502D075D%21155008&parId=FD8073F3502D075D%21155006&o=OneUp
https://onedrive.live.com/?cid=FD8073F3502D075D&id=FD8073F3502D075D%21155007&parId=FD8073F3502D075D%21155006&o=OneUp

**Comment by xoofx** [comment]
They are simply not mapped. Their constructors need to be added (and the relevant mapping.xml files likely modified). I don't have time dedicated for this but PR are welcome.

**Comment by mrvux** [comment]
As a side note, issue here is that you only have one point of entry (eg : D2D1CreateFactory for Direct2D factory). There an no constructors for any of the other versions in the c++ APIs. 

That's why they are not mapped, they just do not exist.

You need to use QueryInterface to request the overloaded version (since depending on OS version, not all of them might be available).

So in case of Direct2D, you need to do : 
SharpDX.Direct2D1.Factory factory = new SharpDX.Direct2D1.Factory();
SharpDX.Direct2D1.Factory3 factory3 = factory.QueryInterface<SharpDX.Direct2D1.Factory3>();

Please note that QueryInterface performs an AddRef internally, so you need to ensure to both dispose 
factory and factory3

Maybe we can create new constructors so they do query interface (to check that they are valid) straight away and release the initial factory (so disposing it will release the last refcounter)?

**Comment by xoofx** [comment]
Good catch, thanks @mrvux completely forgot that it is the behavior with this API. No need to add a constructor, as Direct2D C++ samples should do a QueryInterface, we should keep the same now (departing from the old principle of SlimDX/SharpDX that remapped these as constructors...)
