### ISSUE TITLE
Proposal: Add interfaces to SharpDX classes to support unit testing

### ISSUE THREAD

**Issue by gareththegeek** [sharpdx/SharpDX#885]
I think it would be great if classes within SharpDX each implemented a corresponding interface as this would make it possible to unit test code which consumes SharpDX libraries.

For example, the Device class could implement the IDevice interface which would contain all public methods of the Device class.

If I did this for a project I am working on, would you appreciate a pull request?

**Comment by xoofx** [comment]
I'm going to decline this proposal. 

The reason is that SharpDX is just a native library wrapper, it provides a bunch of DllImport. It doesn't provide an abstraction of the API (or very small, by C#ifying the C++ API).  Many APIs are typically static functions calling directly a DllImport. We don't want to provide an abstraction layer on top of these.

Also, the granularity of the vast majority of DirectX interfaces is so thin that it would take an enormous amount of job to provide a proper mock of theses interfaces (mocking a ID3D11Device would be a huge amount of work... - considering that you would have most likely to mock also DXGI -  I'm not aware of any project doing such a work around Direct3D11)

Usually, a project using SharpDX is using just a small subset of the DirectX interfaces and methods, and it is more recommended to make an internal and mockable facade/interface/class on your side around the SharpDX interfaces, based exactly on what you are using instead of trying to mock everything.
