### ISSUE TITLE
SharpDX.DirectWrite.FontFallback.MapCharacters has incorrect parameter

### ISSUE THREAD

**Issue by jclin** [sharpdx/SharpDX#897]
I was going to write a public wrapper for `MapCharacters_` but noticed one paramter is incorrect. The method signature generated is:
```c#
internal void MapCharacters_(
   System.IntPtr analysisSource, 
   int textPosition, 
   int textLength, 
   SharpDX.DirectWrite.FontCollection baseFontCollection, 
   string baseFamilyName, 
   SharpDX.DirectWrite.FontWeight baseWeight, 
   SharpDX.DirectWrite.FontStyle baseStyle, 
   SharpDX.DirectWrite.FontStretch baseStretch, 
   int mappedLength, 
   out SharpDX.DirectWrite.Font mappedFont, 
   out float scale
) 
```

However, `mappedLength` should be an out parameter per the [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280480%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).  Is there a way for me to fix this on my end without having to tamper with the C# code generation?

**Comment by xoofx** [comment]
This is usually fixed in the [mapping.xml](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml) file by adding a line like:

```
 <map param="IDWriteFontFallback::MapCharacters::mappedLength" attribute="out" />
```

The `mappedLength` must match exactly what is in the dwrite header file (sometimes the msdn doc might be off or not accurate).

Also, the parameter `analysisSource` is a special interface ([callback from c++ to C#](https://github.com/sharpdx/SharpDX/blob/5e9be875a9c0abc3b40c04c398f8d94212c9f3db/Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml#L173)), so you will have to handle it differently - it should be used elsewhere in the code so you can have a look at it)

**Comment by jclin** [comment]
👍, thanks!
