### ISSUE TITLE
Interfaces should be prefixed with "I"

### ISSUE THREAD

**Issue by Axiverse** [sharpdx/SharpDX#905]
Following .NET convention, interfaces should start with I. I'm especially looking around DirectWrite font collections like the interfaces FontCollectionLoader and FontFileLoader. Is there any reason why they shouldn't be prefixed?

**Comment by xoofx** [comment]
Because COM interfaces in SharpDX were mapped automatically by removing the I, as they are mainly used as "concrete class" like `Direct3D11.Device` or `DirectWrite.Factory`. For some callback interfaces - that can have both a concrete class and can be user implemented this is the same. And for purely user implemented interfaces, the code generator from C++ kept also the same rules. There was also in the old age of the library to keep compatibility API with SlimDX.

So it is mostly a legacy choice with some constraints, but as SharpDX is now in maintenance mode, won't make any changes related to this.
