### ISSUE TITLE
Version 4's lack of strong naming is a hardship

### ISSUE THREAD

**Issue by jnm2** [sharpdx/SharpDX#912]
Please continue strong-naming. For companies that need some assemblies to be strong named, this leaves us no option but to create modified SharpDX DLLs. Using SharpDX in our build process is no longer as simple as a package reference.

It's unusual for a top library on NuGet to not be signed. People that don't need signing won't care either way, but life just got a little worse for those of us who do.

Thanks for considering! ❤️

**Comment by xoofx** [comment]
Well, this is a bug when switching to `appveyor.yml`  while previously the config was private on appveyor. The snk file was written from the config, but it seems that I forgot to port it to `appveyor.yml`

I always thought that people would try the pre-release version of SharpDX in order to report this problem... should have maybe insist on the twitter feed to encourage users to do this...

**Comment by jnm2** [comment]
@xoofx I'm glad to hear it wasn't intentional! Twitter is not a bad idea, would have worked for me. Another idea for this particular scenario is a build-time check which fails the build if there are any unsigned assemblies about to be packed or published.

**Comment by xoofx** [comment]
strange, while checking the log, we are actually signing assemblies... not sure what is going on... will have to investigate a bit more...

**Comment by jnm2** [comment]
Whatever got uploaded to NuGet in the `net45` folders was not signed. The ones I checked are SharpDX, SharpDX.DXGI, SharpDX.Direct2D1 and SharpDX.Direct3D11.

**Comment by xoofx** [comment]
I have pushed 4.0.1. This should hopefully fix this

**Comment by jnm2** [comment]
Thanks for the fast resolution!
