### ISSUE TITLE
Direct3D11 How can i rotate a image?

### ISSUE THREAD

**Issue by MazeThePlayer** [sharpdx/SharpDX#986]
Hello could someone please tell me where sprite in Direct3D11?
i have am currently rendering an image, i am can move it but i cant figure how i can rotate it and i cant find a solution anywhere.
This is the code i am using:
`                        Sprite NewSprite = Component as Sprite;
                        Bitmap Texture = Game.bitmapManager.GetTexture(NewSprite.texture.TexturePath);
                        RawRectangleF PositionRectangle = new Rectangle(new Point(gameObject.transform.Position), new Size(NewSprite.texture.TextureSize * Zoom)).ToRawRectangleF();
                        float Transparency = NewSprite.Transparency;
                        RawRectangleF ImageRectangle = new Rectangle(new Point(0,0), new Size(NewSprite.texture.TextureSize * Zoom)).ToRawRectangleF();
                        renderTarget.DrawBitmap(Texture, PositionRectangle, Transparency,BitmapInterpolationMode.NearestNeighbor, ImageRectangle);
`
Sprite, Rectangle, Point and Size custom classes i made

**Comment by Skyppid** [comment]
Since you're using Sprite and stuff I assume you're using Direct2D to draw your image. If so, then you should check out this MSDN [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ff684172(v=vs.85).aspx). Basically you have to apply the transformation in form of a Matrix before you render your image.

**Comment by MazeThePlayer** [comment]
@Skyppid it is now working thank-you the documentation was very helpful.
