### ISSUE TITLE
DataStream doesn't follow Dispose() pattern regarding the unmanaged references

### ISSUE THREAD

**Issue by aienabled** [sharpdx/SharpDX#996]
Hello!

`DataStream` has a `_gCHandle` field which will be never released for abandoned (collected with GC) instance as there is no finalizer defined.

I've noticed a memory leak in MonoGame related to this issue in the way I use `SoundEffect` class from here (by keeping it abandoned and relying on GC).
I understand that `DataStream` might have been never intended to be used the way it's used there and that if used with `using` or `try-finally` patterns controlling auto disposal it should not be a problem, however it's a public API of SharpDX and so there should be never a possibility for memory leaks related to the unmanaged resources.
Also, I see no point of having a properly implemented `Dispose(disposing)` method when it's never called with `disposing==false` (as there is no finalizer in this and parent classes) - maybe you just forgot/missed that `System.IO.Stream` doesn't have a finalizer and it's up to derived class to implement it?

The issue could be completely resolved by adding to `DataStream.cs`:

```C#
~DataStream()
{
     Dispose(false);
}
```

~~And `GC.SuppressFinalize(this);` at the end of the Dispose method.~~

~~I could create a pull request if needed.~~ (Created!)

Regards!

**Comment by xoofx** [comment]
Yeah, at that time, `DataStream` was imported from SlimDX... so I believe it was left as it was exposed there...
There are also two other reasons why It has been updated:
- There is a story in SharpDX to not dispose object automatically for you via finalizers, mainly because many COM problems can arise for certain API (releasing on another thread, heard many stories about this, while myself never confronted to it)
- I have never used `DataStream` in any projects when using SharpDX, so it's a reason why it hasn't received much attention

Though PR welcome and going to be merged! ;)
